# Generated by Django 2.0.2 on 2018-07-07 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AktualneWyniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciezka', models.TextField(blank=True, null=True)),
                ('nazwa', models.CharField(blank=True, max_length=80, null=True, verbose_name='nazwa')),
                ('FPS', models.FloatField(default=0.0, verbose_name='fps')),
                ('dlugosc', models.TimeField(blank=True, null=True, verbose_name='dlugosc')),
                ('rozmiarX', models.IntegerField(default=0, verbose_name='x')),
                ('rozmiarY', models.IntegerField(default=0, verbose_name='y')),
                ('iloscKlatek', models.IntegerField(blank=True, null=True, verbose_name='iloscKlatek')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FilmWynik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciezka', models.TextField()),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainServer.Film')),
            ],
        ),
        migrations.CreateModel(
            name='FolderFilmy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciezka', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FolderZObrazami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciezka', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Klatka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='mainServer.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Obraz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=80, verbose_name='nazwa')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.FolderFilmy')),
                ('klatka', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainServer.Klatka')),
            ],
        ),
        migrations.CreateModel(
            name='ParametryUczenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_rate', models.FloatField(blank=True, default=0.0001, null=True)),
                ('batch_size', models.IntegerField(blank=True, default=64, null=True)),
                ('dropout', models.FloatField(blank=True, default=0.5, null=True)),
                ('iloscIteracji', models.IntegerField(blank=True, default=10000, null=True)),
                ('opisUczeniaXML', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaPunktu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycjaX', models.IntegerField(default=0, verbose_name='x')),
                ('pozycjaY', models.IntegerField(default=0, verbose_name='y')),
                ('klatka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycja', to='mainServer.Klatka')),
            ],
        ),
        migrations.CreateModel(
            name='Sesja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('nazwa', models.TextField(default='Nienazwana_<django.db.models.fields.AutoField>__2018-07-07 20:07:25.710256+00:00')),
                ('filmyPrzetworzone', models.ManyToManyField(blank=True, related_name='sesjaPrzetworzone', to='mainServer.Film')),
                ('filmyUzytkownik', models.ManyToManyField(blank=True, related_name='sesjaUzytkownika', to='mainServer.Film')),
                ('folderZObrazami', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainServer.FolderZObrazami')),
            ],
        ),
        migrations.CreateModel(
            name='Sieci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opisXML', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='StatusFilmu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusPozycji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Uczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusNauki', models.CharField(choices=[('N', 'do nauczania'), ('K', 'ukonczono nauke')], default='N', max_length=1)),
                ('opis', models.TextField(blank=True, null=True)),
                ('parametry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.ParametryUczenia')),
            ],
        ),
        migrations.CreateModel(
            name='WynikPrzetwarzania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wspolrzednaX', models.FloatField()),
                ('wspolrzednaY', models.FloatField()),
                ('numer', models.IntegerField(default=0)),
                ('nazwa', models.CharField(default='', max_length=80, verbose_name='nazwa')),
                ('klatka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainServer.Klatka')),
            ],
        ),
        migrations.CreateModel(
            name='WynikUczenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciezkaDoSieci', models.TextField()),
                ('mean', models.FloatField(blank=True, default=0.0, null=True)),
                ('std', models.FloatField(blank=True, default=0.0, null=True)),
                ('minMeanWTrakcieNauki', models.FloatField(blank=True, default=0.0, null=True)),
                ('histogram', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ZbioryDanych',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.Sesja')),
                ('testowy', models.ManyToManyField(blank=True, related_name='zbioryTestowy', to='mainServer.Obraz')),
                ('uczacy', models.ManyToManyField(related_name='zbioryUczacy', to='mainServer.Obraz')),
                ('walidacyjny', models.ManyToManyField(blank=True, related_name='zbioryWalidacyjny', to='mainServer.Obraz')),
            ],
        ),
        migrations.AddField(
            model_name='uczenie',
            name='wynik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainServer.WynikUczenia'),
        ),
        migrations.AddField(
            model_name='pozycjapunktu',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pozycja', to='mainServer.StatusPozycji'),
        ),
        migrations.AddField(
            model_name='parametryuczenia',
            name='modelSieci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.Sieci'),
        ),
        migrations.AddField(
            model_name='parametryuczenia',
            name='zbiory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.ZbioryDanych'),
        ),
        migrations.AddField(
            model_name='folderfilmy',
            name='sesja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.Sesja'),
        ),
        migrations.AddField(
            model_name='filmwynik',
            name='wynikUczenia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.WynikUczenia'),
        ),
        migrations.AddField(
            model_name='film',
            name='sesja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.Sesja'),
        ),
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.ManyToManyField(blank=True, to='mainServer.StatusFilmu'),
        ),
    ]
