# Generated by Django 2.0.2 on 2018-07-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0002_auto_20180707_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_<django.db.models.fields.AutoField>__2018-07-07 20:34:44.414046+00:00'),
        ),
    ]
