# Generated by Django 2.0.2 on 2018-07-10 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0004_auto_20180707_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesja',
            name='ostatniaAktualizacja',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_<django.db.models.fields.AutoField>__2018-07-10 18:03:25.145050+00:00'),
        ),
    ]
