# Generated by Django 2.0.2 on 2018-07-14 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0005_auto_20180710_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obraz',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='obraz',
            name='klatka',
        ),
        migrations.AddField(
            model_name='klatka',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='klatka',
            name='sciezka',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-07-14 09:44:46.475306+00:00'),
        ),
        migrations.AlterField(
            model_name='zbiorydanych',
            name='testowy',
            field=models.ManyToManyField(blank=True, related_name='zbioryTestowy', to='mainServer.Klatka'),
        ),
        migrations.AlterField(
            model_name='zbiorydanych',
            name='uczacy',
            field=models.ManyToManyField(related_name='zbioryUczacy', to='mainServer.Klatka'),
        ),
        migrations.AlterField(
            model_name='zbiorydanych',
            name='walidacyjny',
            field=models.ManyToManyField(blank=True, related_name='zbioryWalidacyjny', to='mainServer.Klatka'),
        ),
        migrations.DeleteModel(
            name='Obraz',
        ),
    ]
