# Generated by Django 2.0.2 on 2018-07-31 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0006_auto_20180714_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderZPrzygotowanymiObrazami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciezka', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ObrazPoDostosowaniu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wspResize', models.FloatField(default=1.0)),
                ('sciezka', models.TextField(default='')),
                ('metoda', models.CharField(choices=[('V', 'flipped vertical'), ('H', 'flipped horizontal'), ('O', 'orginal')], max_length=1)),
                ('klatkaMacierzysta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.Klatka')),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaCropa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycjaX', models.IntegerField(default=0, verbose_name='x')),
                ('pozycjaY', models.IntegerField(default=0, verbose_name='y')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PozycjaPunktuPoCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycjaX', models.IntegerField(default=0, verbose_name='x')),
                ('pozycjaY', models.IntegerField(default=0, verbose_name='y')),
                ('obraz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycja', to='mainServer.ObrazPoDostosowaniu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusPozycjiCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZlecenieAugmentacji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodAugmentacji', models.IntegerField(default=114)),
                ('oczekiwanyRozmiarX', models.IntegerField(verbose_name='x')),
                ('oczekiwanyRozmiarY', models.IntegerField(verbose_name='y')),
                ('wTrakcie', models.BooleanField(default=False)),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainServer.FolderZPrzygotowanymiObrazami')),
                ('klatka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.Klatka')),
            ],
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-07-31 19:12:06.913693+00:00'),
        ),
        migrations.AddField(
            model_name='pozycjapunktupocrop',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pozycja', to='mainServer.StatusPozycjiCrop'),
        ),
        migrations.AddField(
            model_name='obrazpodostosowaniu',
            name='pozycjaCropa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obraz', to='mainServer.PozycjaCropa'),
        ),
    ]
