# Generated by Django 2.0.2 on 2018-07-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0007_auto_20180731_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-07-31 19:13:34.375638+00:00'),
        ),
    ]
