# Generated by Django 2.0.2 on 2018-08-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0009_auto_20180809_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-08-09 19:24:22.332977+00:00'),
        ),
        migrations.AlterField(
            model_name='uczenie',
            name='statusNauki',
            field=models.CharField(choices=[('N', 'do nauczania'), ('T', 'w trakcie'), ('K', 'ukonczono nauke')], default='N', max_length=1),
        ),
    ]
