# Generated by Django 2.0.2 on 2018-08-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0010_auto_20180809_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pozycjacropa',
            old_name='pozycjaX',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='pozycjacropa',
            old_name='pozycjaY',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='pozycjapunktu',
            old_name='pozycjaX',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='pozycjapunktu',
            old_name='pozycjaY',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='pozycjapunktupocrop',
            old_name='pozycjaX',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='pozycjapunktupocrop',
            old_name='pozycjaY',
            new_name='y',
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-08-11 20:55:42.685156+00:00'),
        ),
    ]
