# Generated by Django 2.0.2 on 2018-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0011_auto_20180811_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='sieci',
            name='inputSizeX',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sieci',
            name='inputSizeY',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-08-18 20:00:38.057308+00:00'),
        ),
    ]
