# Generated by Django 2.0.2 on 2018-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0012_auto_20180818_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametryuczenia',
            name='epochSize',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='parametryuczenia',
            name='saveStep',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-08-18 20:14:39.345693+00:00'),
        ),
    ]
