# Generated by Django 2.0.2 on 2018-09-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0013_auto_20180818_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wynikuczenia',
            old_name='minMeanWTrakcieNauki',
            new_name='max',
        ),
        migrations.RenameField(
            model_name='wynikuczenia',
            old_name='sciezkaDoSieci',
            new_name='model_file',
        ),
        migrations.AddField(
            model_name='wynikuczenia',
            name='errors',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='wynikuczenia',
            name='min_mean_during_learning',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-09-03 08:26:49.139615+00:00'),
        ),
    ]
