# Generated by Django 2.0.2 on 2018-09-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0014_auto_20180903_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-09-03 21:14:37.181986+00:00'),
        ),
        migrations.AlterField(
            model_name='uczenie',
            name='wynik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learn', to='mainServer.WynikUczenia'),
        ),
    ]
