# Generated by Django 2.1.1 on 2018-09-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0018_auto_20180904_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrazpodostosowaniu',
            name='zlecenie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainServer.ZlecenieAugmentacji'),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-09-18 04:48:37.218216+00:00'),
        ),
    ]
