# Generated by Django 2.1.1 on 2018-09-18 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0019_auto_20180918_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-09-18 05:39:16.389606+00:00'),
        ),
        migrations.AlterField(
            model_name='zlecenieaugmentacji',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainServer.FolderZPrzygotowanymiObrazami'),
        ),
    ]
