# Generated by Django 2.1.1 on 2018-09-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0021_auto_20180927_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='klatka',
            name='nazwa',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='klatka',
            name='sciezka',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-09-27 19:01:02.573651+00:00'),
        ),
    ]
