# Generated by Django 2.1.1 on 2018-09-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0022_auto_20180927_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrazpodostosowaniu',
            name='nazwa',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='obrazpodostosowaniu',
            name='sciezka',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-09-27 21:00:32.359682+00:00'),
        ),
    ]
