# Generated by Django 2.1.1 on 2018-11-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0023_auto_20180927_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kolor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='nazwa')),
                ('kod', models.CharField(blank=True, max_length=100, null=True, verbose_name='kod')),
            ],
        ),
        migrations.AddField(
            model_name='uczenie',
            name='zbiory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainServer.ZbioryDanych'),
        ),
        migrations.AlterField(
            model_name='parametryuczenia',
            name='zbiory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainServer.ZbioryDanych'),
        ),
        migrations.AlterField(
            model_name='pozycjacropa',
            name='x',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='x'),
        ),
        migrations.AlterField(
            model_name='pozycjacropa',
            name='y',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='y'),
        ),
        migrations.AlterField(
            model_name='pozycjapunktu',
            name='x',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='x'),
        ),
        migrations.AlterField(
            model_name='pozycjapunktu',
            name='y',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='y'),
        ),
        migrations.AlterField(
            model_name='pozycjapunktupocrop',
            name='x',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='x'),
        ),
        migrations.AlterField(
            model_name='pozycjapunktupocrop',
            name='y',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='y'),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-11-12 22:09:08.384606+00:00'),
        ),
        migrations.AlterField(
            model_name='statusfilmu',
            name='status',
            field=models.CharField(max_length=100, unique=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='statuspozycji',
            name='status',
            field=models.CharField(max_length=100, unique=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='statuspozycjicrop',
            name='status',
            field=models.CharField(max_length=100, unique=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='pozycjapunktu',
            name='kolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pozycja', to='mainServer.Kolor'),
        ),
        migrations.AddField(
            model_name='pozycjapunktupocrop',
            name='kolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pozycjaCrop', to='mainServer.Kolor'),
        ),
        migrations.AddField(
            model_name='uczenie',
            name='kolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uczenie', to='mainServer.Kolor'),
        ),
        migrations.AddField(
            model_name='zbiorydanych',
            name='kolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zbioryDanych', to='mainServer.Kolor'),
        ),
        migrations.AddField(
            model_name='zlecenieaugmentacji',
            name='kolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zlecenie', to='mainServer.Kolor'),
        ),
    ]
