# Generated by Django 2.1.1 on 2018-11-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0024_auto_20181112_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uczenie',
            name='kolor',
        ),
        migrations.RemoveField(
            model_name='zlecenieaugmentacji',
            name='kolor',
        ),
        migrations.AddField(
            model_name='obrazpodostosowaniu',
            name='kolor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainServer.Kolor'),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2018-11-23 15:41:55.019149+00:00'),
        ),
    ]
