# Generated by Django 2.1.5 on 2019-01-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0025_auto_20181123_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZbiorKolorow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='nazwa')),
                ('kolory', models.ManyToManyField(blank=True, to='mainServer.Kolor')),
                ('domyslny_kolor', models.ForeignKey(blank=True, null='True', on_delete=models.deletion.SET_NULL, related_name='zbior_domyslny_kolor', to='mainServer.Kolor'))
            ],
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2019-01-20 18:33:21.572117+00:00'),
        ),
    ]
