# Generated by Django 2.1.5 on 2019-02-09 15:26

from django.db import migrations, models
import django.db.models.deletion
from mainServer.models import *


def colorSetPk():
    return ZbiorKolorow.objects.get(nazwa="Domyslny zestaw").pk


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0026_v2_add_all_default_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesja',
            name='zbiorKolorow',
            field=models.ForeignKey(blank=True, default=colorSetPk, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainServer.ZbiorKolorow'),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2019-02-09 15:26:07.464348+00:00'),
        ),
    ]
