# Generated by Django 2.2.1 on 2019-05-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0027_v1_add_default_colorset_to_old_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pozycjapunktupocrop',
            name='kolor',
        ),
        migrations.RemoveField(
            model_name='pozycjapunktupocrop',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pozycjapunktupocrop',
            name='x',
        ),
        migrations.RemoveField(
            model_name='pozycjapunktupocrop',
            name='y',
        ),
        migrations.AddField(
            model_name='pozycjapunktupocrop',
            name='json',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2019-05-15 19:40:51.130882+00:00'),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='zbiorKolorow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainServer.ZbiorKolorow'),
        ),
    ]
