# Generated by Django 2.2.1 on 2019-05-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0029_auto_20190515_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrazpodostosowaniu',
            name='kolor',
        ),
        migrations.RemoveField(
            model_name='obrazpodostosowaniu',
            name='wspResize',
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2019-05-15 21:07:15.698754+00:00'),
        ),
    ]
