# Generated by Django 2.2.1 on 2019-05-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0030_auto_20190515_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametryuczenia',
            name='opisUczeniaXML',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2019-05-23 19:56:31.058251+00:00'),
        ),
    ]
