# Generated by Django 2.2.1 on 2019-05-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainServer', '0033_auto_20190525_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesja',
            name='nazwa',
            field=models.TextField(default='Nienazwana_2019-05-27 22:08:21.388185+00:00'),
        ),
    ]
